name: kuiqly
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: 0.24.0
  dio: ^3.0.8
  intl: ^0.16.1
  charts_flutter: ^0.8.1
  shared_preferences: 0.5.6+3
  font_awesome_flutter: ^8.8.1
  equatable: ^1.1.0
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  table_calendar: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/21.jpg
    - images/avatar.jpg
    - images/icons/ic_mail.png
    - images/icons/ic_phone.png
    - images/icons/ic_back.png
    - images/icons/ic_back_white.png
    - images/icons/ic_user.png
    - images/icons/ic_notification.png
    - images/icons/ic_faceid.png
    - images/icons/ic_settings.png
    - images/icons/ic_arrow_down.png
    - images/icons/ic_Grab.png
    - images/icons/ic_arrow_right.png
    - images/icons/avatar.png
    - images/icons/ic_chart.png
    - images/icons/ic_chart.png
    - images/icons/ic_filter.png
    - images/icons/ic_menu.png
    - images/icons/ic_wallet.png
    - images/icons/ic_wallet_active.png
    - images/icons/logo.png
    - images/icons/splash_logo.png
    - images/onboarding_1.png
    - images/onboarding_2.png
    - images/onboarding_3.png
    - images/icons/ic_category.png
    - images/icons/ic_help.png
    - images/icons/ic_report.png
    - images/icons/ic_theme.png
    - images/icons/ic_policy.png
    - images/icons/ic_logout.png
    - images/icons/ic_message.png
    - images/icons/ic_calendar.png
    - images/icons/ic_close.png
    - images/icons/ic_done.png
    - images/icons/ic_memo.png
    - images/icons/ic_friends.png
    - images/icons/ic_location.png
    - images/icons/ic_plus.png
    - images/icons/ic_cash.png
    - images/icons/ic_debit_card.png
    - images/icons/ic_credit_card.png
    - images/icons/ic_bank.png
    - images/icons/ic_amount.png
    - images/icons/ic_curency.png
    - images/icons/ic_credit_card_large.png
    - images/icons/ic_scan.png
    - images/icons/ic_pro.png
    - images/icons/btn_close.png
    - images/ic_money_wallet.png
    - images/ic_strongbox.png
    - images/ic_bars.png
    - images/icons/ic_Family.png
    - images/icons/ic_Gaming.png
    - images/icons/ic_Gas.png
    - images/icons/ic_Lover.png
    - images/icons/ic_Poker.png
    - images/icons/ic_Restaurant.png
    - images/icons/ic_Shopping.png
    - images/icons/ic_Uber.png
    - images/icons/ic_add.png
    - images/icons/ic_calendar.png
    - images/icons/ic_cinema.png
    - images/icons/ic_coffee.png
    - images/icons/ic_travel.png

  fonts:
    - family: SanFransisco
      fonts:
        - asset: fonts/SF/SF-Pro-Display-Regular.otf
        - asset: fonts/SF/SF-Pro-Display-Light.otf
        - asset: fonts/SF/SF-Pro-Display-Medium.otf
        - asset: fonts/SF/SF-Pro-Display-Bold.otf
        - asset: fonts/SF/SF-Pro-Display-Semibold.otf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Bold.ttf
        - asset: fonts/Quicksand/Quicksand-Light.ttf
        - asset: fonts/Quicksand/Quicksand-Medium.ttf
        - asset: fonts/Quicksand/Quicksand-Regular.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
